import "@uploadthing/react/styles.css";
import "~/styles/globals.css";


import { type Metadata } from "next";
import { Roboto, Poppins } from "next/font/google";
import { ScrollToTop } from "~/components/common/scroll-top";
import { Header } from "~/components/general/header";
import { Toaster } from "~/components/ui/toaster";
import Provider from "~/app/provider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-text",
});

const poppin = Poppins({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Artstay - A Project of DKC",
  description: "Generated by create-t3-app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${roboto.variable} ${poppin.variable}`}>
      <body>
        <Provider>
          <Header />
          <main>{children}</main>
          <Toaster />
          <ScrollToTop />
        </Provider>
      </body>
    </html>
  );
}
